# SPDX-License-Identifier: GPL-2.0-only
obj-m += dreem_eeg_research.o
dreem_eeg_research-y := adc_linux.o ads129x_init.o
ccflags-y += -std=gnu99 -Wno-declaration-after-statement -msoft-float -fno-tree-vectorize -Werror
